R11.drawKeys = {
    "pc": {
        "left": "shiftLeft",
        "right": "shiftRight",
        "up": "shiftUp",
        "down": "shiftDown",
        ".": "gridExpand",
        ",": "gridReduce",
        "K": "zoomout",
        "L": "zoomin",
        "G": "toggleGrid",
        "Q": "eraserOn",
        "W": "eraserOff",
        "S": "save",
        "[": "prevChart",
        "]": "nextChart",
        "C": "clearSaves",
        "A": "drawLine",
        "E": "eraser",
        "F": "gridShift"
    },
    "wiiuBrowser": {
        "+": "zoomin",
        "-": "zoomout",
        "A": "ballOn",
        "left": "prevChart",
        "right": "nextChart",
        "Lstick": "gridOff",
        "Rstick": "gridOn",
        "up": "gridExpand",
        "down": "gridReduce",
    },
    "wiiu": {
        "+": "zoomin",
        "-": "zoomout",
        "R": "save",
        "up": "shiftUp",
        "down": "shiftDown",
        "left": "shiftLeft",
        "right": "shiftRight",
        "Lstick": "gridOff",
        "Rstick": "gridOn",
        "ZL": "toggleGrid",
        "B": "gridReduce",
        "A": "nextChart",
        "X": "gridExpand",
        "Y": "prevChart",
        "ZR": "chartClose",
        "L": "chartClose",
    }
}